(() => {
  const clean=v=>String(v??'').trim();
  const norm=v=>clean(v).toLowerCase().replace(/δ|Δ/g,'delta ').replace(/θ/g,'theta').replace(/ρ/g,'rho').replace(/λ/g,'lambda').replace(/²/g,'^2').replace(/…/g,'...').replace(/\s+/g,' ');
  const symbols={
    m:['mass','kg'],v:['speed / velocity','m/s'],u:['initial velocity','m/s'],a:['acceleration','m/s²'],t:['time','s'],s:['distance / displacement','m'],h:['height','m'],g:['gravitational field strength','N/kg'],
    e:['energy','J'],ek:['kinetic energy','J'],ep:['gravitational potential energy','J'],ee:['elastic potential energy','J'],p:['power or pressure (check context)','W or Pa'],w:['work done','J'],f:['force','N'],k:['spring constant','N/m'],
    q:['charge','C'],i:['current','A'],r:['resistance','Ω'],V:['potential difference','V'],I:['current','A'],R:['resistance','Ω'],E:['energy','J'],P:['power','W'],Q:['charge','C'],
    rho:['density','kg/m³'],c:['specific heat capacity','J/kg°C'],L:['specific latent heat','J/kg'],A:['area','m²'],d:['distance','m'],lambda:['wavelength','m'],f_wave:['frequency','Hz'],T:['period','s'],
    mr:['relative formula mass','no unit'],n:['amount of substance','mol'],conc:['concentration','mol/dm³ or g/dm³ depending on equation'],vol:['volume','dm³ or m³ depending on equation']
  };

  const profiles=[
    {rx:/ek\s*=.*m.*v\^?2/,meaning:'Kinetic energy depends on mass and on the square of speed.',vars:[['Ek','kinetic energy','J'],['m','mass','kg'],['v','speed','m/s']],rearrange:['v = √(2Ek/m)','m = 2Ek/v²'],worked:['A 2 kg object moves at 3 m/s.','Ek = ½mv²','Ek = 0.5 × 2 × 3²','Ek = 9 J'],scaffold:'Calculate the kinetic energy of a 4 kg object moving at 5 m/s.',independent:'A car has kinetic energy 160 kJ and mass 800 kg. Calculate its speed.',exam:'Explain why doubling speed has a larger effect on kinetic energy than doubling mass.'},
    {rx:/ep\s*=\s*mgh/,meaning:'Gravitational potential energy changes when a mass changes height in a gravitational field.',vars:[['Ep','gravitational potential energy','J'],['m','mass','kg'],['g','gravitational field strength','N/kg'],['h','height','m']],rearrange:['h = Ep/(mg)','m = Ep/(gh)'],worked:['A 3 kg mass is raised 2 m where g = 9.8 N/kg.','Ep = mgh','Ep = 3 × 9.8 × 2','Ep = 58.8 J'],scaffold:'Calculate the GPE gained by a 5 kg mass raised 4 m using g = 9.8 N/kg.',independent:'A climber gains 14.7 kJ of GPE by climbing 25 m. Calculate the climber’s mass.',exam:'Explain how energy stores change when an object falls.'},
    {rx:/ee\s*=.*k.*e\^?2/,meaning:'Elastic potential energy stored in a spring depends on spring constant and the square of extension.',vars:[['Ee','elastic potential energy','J'],['k','spring constant','N/m'],['e','extension','m']],rearrange:['e = √(2Ee/k)','k = 2Ee/e²'],worked:['A spring with k = 200 N/m extends by 0.10 m.','Ee = ½ke²','Ee = 0.5 × 200 × 0.10²','Ee = 1.0 J'],scaffold:'Calculate energy stored when k = 150 N/m and extension = 0.20 m.',independent:'A spring stores 2.5 J when extended 0.10 m. Calculate k.',exam:'Explain why extension must be converted to metres before using the equation.'},
    {rx:/delta e\s*=\s*mc.*delta theta/,meaning:'Thermal energy change depends on mass, specific heat capacity and temperature change.',vars:[['ΔE','energy transferred','J'],['m','mass','kg'],['c','specific heat capacity','J/kg°C'],['Δθ','temperature change','°C']],rearrange:['c = ΔE/(mΔθ)','m = ΔE/(cΔθ)','Δθ = ΔE/(mc)'],worked:['2 kg of water, c = 4200 J/kg°C, warms by 5°C.','ΔE = mcΔθ','ΔE = 2 × 4200 × 5','ΔE = 42 000 J'],scaffold:'Calculate the energy needed to heat 0.5 kg of water by 20°C.',independent:'A 1.5 kg block gains 13.5 kJ and warms by 30°C. Calculate c.',exam:'State two measurements needed in a specific heat capacity practical and one source of uncertainty.'},
    {rx:/^p\s*=\s*e\/t$|^p\s*=\s*w\/t$/,meaning:'Power is the rate of energy transfer or work done.',vars:[['P','power','W'],['E / W','energy transferred / work done','J'],['t','time','s']],rearrange:['E = Pt','t = E/P'],worked:['600 J is transferred in 3 s.','P = E/t','P = 600/3','P = 200 W'],scaffold:'A device transfers 2400 J in 8 s. Calculate its power.',independent:'A 1.2 kW heater transfers 360 kJ. Calculate the time.',exam:'Compare two devices that transfer the same energy in different times.'},
    {rx:/efficiency\s*=.*useful.*total/,meaning:'Efficiency compares useful output with total input.',vars:[['efficiency','useful output ÷ total input','decimal or %']],rearrange:['useful output = efficiency × total input','total input = useful output ÷ efficiency'],worked:['A device transfers 800 J and 600 J is useful.','efficiency = useful/total','efficiency = 600/800','efficiency = 0.75 = 75%'],scaffold:'Calculate the efficiency of a device with 350 J useful output from 500 J input.',independent:'A motor is 80% efficient and gives 1.6 kJ useful output. Calculate total input.',exam:'Explain where the non-useful energy is transferred.'},
    {rx:/q\s*=\s*it/,meaning:'Charge flow equals current multiplied by time.',vars:[['Q','charge','C'],['I','current','A'],['t','time','s']],rearrange:['I = Q/t','t = Q/I'],worked:['A current of 2 A flows for 5 s.','Q = It','Q = 2 × 5','Q = 10 C'],scaffold:'Calculate charge when 0.5 A flows for 40 s.',independent:'120 C flows in 30 s. Calculate current.',exam:'Explain why current is described as the rate of flow of charge.'},
    {rx:/v\s*=\s*ir/,meaning:'Potential difference equals current multiplied by resistance.',vars:[['V','potential difference','V'],['I','current','A'],['R','resistance','Ω']],rearrange:['I = V/R','R = V/I'],worked:['A 6 Ω resistor carries 2 A.','V = IR','V = 2 × 6','V = 12 V'],scaffold:'Calculate V for I = 0.4 A and R = 15 Ω.',independent:'A component has 9 V across it and current 0.30 A. Calculate resistance.',exam:'Explain what happens to current if resistance increases while potential difference stays constant.'},
    {rx:/rtotal\s*=|r.?total\s*=/,meaning:'In series, total resistance is the sum of component resistances.',vars:[['Rtotal','total resistance','Ω'],['R1, R2…','component resistances','Ω']],rearrange:['R1 = Rtotal − R2 − …'],worked:['Two series resistors are 4 Ω and 6 Ω.','Rtotal = R1 + R2','Rtotal = 4 + 6','Rtotal = 10 Ω'],scaffold:'Find total resistance for 3 Ω, 7 Ω and 10 Ω in series.',independent:'Total series resistance is 25 Ω. One resistor is 8 Ω and another 5 Ω. Find the third.',exam:'Explain why adding a resistor in series increases total resistance.'},
    {rx:/p\s*=\s*vi/,meaning:'Electrical power equals potential difference multiplied by current.',vars:[['P','power','W'],['V','potential difference','V'],['I','current','A']],rearrange:['V = P/I','I = P/V'],worked:['A device uses 12 V and 3 A.','P = VI','P = 12 × 3','P = 36 W'],scaffold:'Calculate the power of a 230 V appliance drawing 2 A.',independent:'A 920 W appliance runs at 230 V. Calculate current.',exam:'Explain what a larger power rating means about energy transfer each second.'},
    {rx:/p\s*=\s*i\^?2r/,meaning:'Electrical power can be calculated from current and resistance.',vars:[['P','power','W'],['I','current','A'],['R','resistance','Ω']],rearrange:['I = √(P/R)','R = P/I²'],worked:['2 A flows through 5 Ω.','P = I²R','P = 2² × 5','P = 20 W'],scaffold:'Calculate power for I = 3 A and R = 4 Ω.',independent:'A resistor dissipates 48 W with resistance 12 Ω. Calculate current.',exam:'Explain why transmission losses increase strongly with current.'},
    {rx:/e\s*=\s*pt/,meaning:'Energy transferred equals power multiplied by time.',vars:[['E','energy','J'],['P','power','W'],['t','time','s']],rearrange:['P = E/t','t = E/P'],worked:['A 100 W device runs for 30 s.','E = Pt','E = 100 × 30','E = 3000 J'],scaffold:'Calculate the energy transferred by a 60 W lamp in 120 s.',independent:'A 2 kW kettle transfers 360 kJ. Calculate time.',exam:'Explain why time must be in seconds when power is in watts and energy is required in joules.'},
    {rx:/e\s*=\s*qv/,meaning:'Energy transferred when charge moves through a potential difference equals charge × potential difference.',vars:[['E','energy','J'],['Q','charge','C'],['V','potential difference','V']],rearrange:['Q = E/V','V = E/Q'],worked:['5 C moves through 12 V.','E = QV','E = 5 × 12','E = 60 J'],scaffold:'Calculate energy transferred when 20 C moves through 6 V.',independent:'240 J is transferred at 12 V. Calculate charge.',exam:'Connect potential difference to energy transferred per unit charge.'},
    {rx:/rho\s*=\s*m\/v/,meaning:'Density is mass per unit volume.',vars:[['ρ','density','kg/m³'],['m','mass','kg'],['V','volume','m³']],rearrange:['m = ρV','V = m/ρ'],worked:['A sample has mass 2 kg and volume 0.001 m³.','ρ = m/V','ρ = 2/0.001','ρ = 2000 kg/m³'],scaffold:'Calculate density for 0.50 kg occupying 0.00025 m³.',independent:'A material has density 8000 kg/m³ and mass 4 kg. Calculate volume.',exam:'Explain how you would determine the density of an irregular solid.'},
    {rx:/e\s*=\s*ml/,meaning:'Energy for a change of state equals mass multiplied by specific latent heat.',vars:[['E','energy','J'],['m','mass','kg'],['L','specific latent heat','J/kg']],rearrange:['m = E/L','L = E/m'],worked:['0.5 kg changes state with L = 200 000 J/kg.','E = mL','E = 0.5 × 200 000','E = 100 000 J'],scaffold:'Calculate energy for 2 kg with L = 330 000 J/kg.',independent:'660 kJ changes the state of 2 kg. Calculate L.',exam:'Explain why temperature stays constant during a change of state.'},
    {rx:/pv\s*=\s*constant/,meaning:'For a fixed mass of gas at constant temperature, pressure × volume is constant.',vars:[['p','pressure','Pa'],['V','volume','m³']],rearrange:['p1V1 = p2V2','p2 = p1V1/V2','V2 = p1V1/p2'],worked:['A gas is at 100 kPa and 4 dm³, compressed to 2 dm³ at constant temperature.','p1V1 = p2V2','p2 = 100 × 4 / 2','p2 = 200 kPa'],scaffold:'A gas at 120 kPa occupies 5 dm³. Find pressure at 3 dm³.',independent:'A gas changes from 2.0 dm³ at 150 kPa to 100 kPa. Calculate final volume.',exam:'Use particle collisions to explain why reducing volume increases pressure at constant temperature.'},
    {rx:/s\s*=\s*vt/,meaning:'Distance travelled at constant speed equals speed multiplied by time.',vars:[['s','distance','m'],['v','speed','m/s'],['t','time','s']],rearrange:['v = s/t','t = s/v'],worked:['A car travels at 12 m/s for 5 s.','s = vt','s = 12 × 5','s = 60 m'],scaffold:'Calculate distance travelled at 8 m/s for 15 s.',independent:'A runner covers 400 m in 50 s. Calculate average speed.',exam:'Explain how the gradient of a distance–time graph gives speed.'},
    {rx:/a\s*=.*v.*u.*t/,meaning:'Acceleration is change in velocity divided by time.',vars:[['a','acceleration','m/s²'],['v','final velocity','m/s'],['u','initial velocity','m/s'],['t','time','s']],rearrange:['v = u + at','u = v − at','t = (v − u)/a'],worked:['Velocity changes from 4 m/s to 10 m/s in 3 s.','a = (v − u)/t','a = (10 − 4)/3','a = 2 m/s²'],scaffold:'Calculate acceleration from 5 m/s to 17 m/s in 4 s.',independent:'An object accelerates at 3 m/s² for 6 s from 2 m/s. Calculate final velocity.',exam:'Explain the difference between speed and velocity.'},
    {rx:/f\s*=\s*ma/,meaning:'Resultant force equals mass multiplied by acceleration.',vars:[['F','resultant force','N'],['m','mass','kg'],['a','acceleration','m/s²']],rearrange:['m = F/a','a = F/m'],worked:['A 5 kg object accelerates at 2 m/s².','F = ma','F = 5 × 2','F = 10 N'],scaffold:'Calculate resultant force for 1200 kg accelerating at 1.5 m/s².',independent:'A resultant force of 900 N gives acceleration 0.75 m/s². Calculate mass.',exam:'Explain how zero resultant force can still be consistent with an object moving.'},
    {rx:/w\s*=\s*mg/,meaning:'Weight is the gravitational force on a mass.',vars:[['W','weight','N'],['m','mass','kg'],['g','gravitational field strength','N/kg']],rearrange:['m = W/g','g = W/m'],worked:['A 10 kg mass is in a field of 9.8 N/kg.','W = mg','W = 10 × 9.8','W = 98 N'],scaffold:'Calculate the weight of a 65 kg person where g = 9.8 N/kg.',independent:'An object weighs 49 N. Calculate its mass using g = 9.8 N/kg.',exam:'Distinguish mass from weight.'},
    {rx:/w\s*=\s*fs/,meaning:'Work done equals force multiplied by distance moved in the direction of the force.',vars:[['W','work done','J'],['F','force','N'],['s','distance','m']],rearrange:['F = W/s','s = W/F'],worked:['A 50 N force moves an object 4 m.','W = Fs','W = 50 × 4','W = 200 J'],scaffold:'Calculate work done by 30 N over 6 m.',independent:'900 J is done moving an object 15 m. Calculate force.',exam:'Explain why work done is an energy transfer.'},
    {rx:/p\s*=\s*mv/,meaning:'Momentum equals mass multiplied by velocity.',vars:[['p','momentum','kg m/s'],['m','mass','kg'],['v','velocity','m/s']],rearrange:['m = p/v','v = p/m'],worked:['A 3 kg object moves at 4 m/s.','p = mv','p = 3 × 4','p = 12 kg m/s'],scaffold:'Calculate momentum for 1200 kg at 15 m/s.',independent:'Momentum is 40 kg m/s for a 5 kg object. Calculate velocity.',exam:'Use conservation of momentum to explain a collision or explosion.'},
    {rx:/f\s*=\s*ke/,meaning:'For a spring obeying Hooke’s law, force is proportional to extension.',vars:[['F','force','N'],['k','spring constant','N/m'],['e','extension','m']],rearrange:['k = F/e','e = F/k'],worked:['A spring with k = 80 N/m extends 0.05 m.','F = ke','F = 80 × 0.05','F = 4 N'],scaffold:'Calculate force for k = 120 N/m and extension 0.08 m.',independent:'A 6 N force extends a spring 0.03 m. Calculate k.',exam:'Explain what the limit of proportionality means on a force–extension graph.'},
    {rx:/moment\s*=|m\s*=\s*fd/,meaning:'Moment equals force multiplied by perpendicular distance from the pivot.',vars:[['moment','turning effect','N m'],['F','force','N'],['d','perpendicular distance','m']],rearrange:['F = moment/d','d = moment/F'],worked:['A 20 N force acts 0.5 m from a pivot.','moment = Fd','moment = 20 × 0.5','moment = 10 N m'],scaffold:'Calculate moment for 35 N acting 0.20 m from a pivot.',independent:'A moment of 18 N m is produced by 60 N. Calculate distance.',exam:'State the condition for an object in rotational equilibrium.'},
    {rx:/p\s*=\s*f\/a/,meaning:'Pressure equals normal force divided by area.',vars:[['p','pressure','Pa'],['F','normal force','N'],['A','area','m²']],rearrange:['F = pA','A = F/p'],worked:['A 200 N force acts over 0.50 m².','p = F/A','p = 200/0.50','p = 400 Pa'],scaffold:'Calculate pressure for 600 N on 0.30 m².',independent:'Pressure is 2500 Pa from a 500 N force. Calculate area.',exam:'Explain why reducing contact area increases pressure for the same force.'},
    {rx:/v\s*=\s*f.*lambda/,meaning:'Wave speed equals frequency multiplied by wavelength.',vars:[['v','wave speed','m/s'],['f','frequency','Hz'],['λ','wavelength','m']],rearrange:['f = v/λ','λ = v/f'],worked:['A wave has frequency 5 Hz and wavelength 2 m.','v = fλ','v = 5 × 2','v = 10 m/s'],scaffold:'Calculate wave speed for 12 Hz and 0.50 m.',independent:'Wave speed is 340 m/s and frequency 680 Hz. Calculate wavelength.',exam:'Explain what changes and what stays constant when a wave crosses a boundary.'},
    {rx:/t\s*=\s*1\/f/,meaning:'Period is the time for one cycle and is the reciprocal of frequency.',vars:[['T','period','s'],['f','frequency','Hz']],rearrange:['f = 1/T'],worked:['A wave has frequency 4 Hz.','T = 1/f','T = 1/4','T = 0.25 s'],scaffold:'Calculate period for 20 Hz.',independent:'A period is 0.005 s. Calculate frequency.',exam:'Connect frequency to number of cycles per second.'}
  ];

  function profileFor(eq){const n=norm(eq);return profiles.find(p=>p.rx.test(n))||null;}
  function generic(eq,subject='science'){
    const text=clean(eq);
    return {equation:text,meaning:`Use ${text} as a quantitative relationship in this ${subject} lesson. Identify what each quantity represents before substituting values.`,vars:[],rearrange:['Choose the required quantity first.','Rearrange algebraically before inserting numbers.'],worked:[`Start from ${text}.`,'Write the known values with units.','Substitute only after units are consistent.','Calculate and check the final unit and significant figures.'],scaffold:`Use ${text} with values supplied by the question. Show the rearrangement and units.`,independent:`Solve an unfamiliar GCSE calculation using ${text}.`,exam:'Explain your calculation route and state the final answer with an appropriate unit.',unitGuidance:'Use the units specified in the lesson and convert values before substitution.'};
  }
  function build(eq,subject='science'){
    const p=profileFor(eq);const base=p?{...p,equation:clean(eq)}:generic(eq,subject);
    return {...base,unitGuidance:base.unitGuidance||'Convert all quantities to compatible SI units before substitution unless the question explicitly uses a consistent alternative.',route:['Meaning','Symbols & units','Rearrange','Substitute','Calculate','Check']};
  }
  function validate(model){return ['equation','meaning','rearrange','worked','scaffold','independent','exam','unitGuidance','route'].filter(k=>!model?.[k]||(Array.isArray(model[k])&&!model[k].length));}
  window.GCSE_EQUATION_COACH={build,validate,profileFor,norm,symbols};
})();