window.GCSE_RICH_CONTENT = (() => {
  const guides = {
    b1:{diagram:'cell',textbook:[
      ['Cell structure and organisation','Animal and plant cells are eukaryotic: their genetic material is enclosed in a nucleus and they contain specialised sub-cellular structures. Bacterial cells are prokaryotic, so their DNA is not enclosed in a nucleus and they are much smaller. Structure links directly to function: mitochondria release energy by aerobic respiration, ribosomes make proteins and chloroplasts absorb light for photosynthesis.'],
      ['Microscopy, magnification and scale','Light microscopes allow cells and tissues to be viewed. Magnification is calculated using magnification = image size ÷ real size, so units must be made consistent before calculating. Electron microscopes have much greater magnification and resolving power and can reveal much smaller structures.'],
      ['Cell division and transport','Mitosis produces two genetically identical cells for growth, repair and replacement. Diffusion moves particles down a concentration gradient, osmosis is the net movement of water through a partially permeable membrane, and active transport moves substances against a concentration gradient using energy from respiration.']
    ],terms:[['resolution','The ability to distinguish two close points as separate.'],['mitosis','Cell division producing two genetically identical daughter cells.'],['osmosis','Net movement of water from a dilute solution to a more concentrated solution through a partially permeable membrane.'],['active transport','Movement against a concentration gradient using energy.']],worked:{title:'Magnification calculation',question:'A cell image is 36 mm long and the real cell is 0.12 mm long. Calculate magnification.',steps:['Use magnification = image size ÷ real size.','36 ÷ 0.12 = 300.','The image is magnified ×300.']},activity:{title:'Cell detective',task:'Compare an animal cell, plant cell and bacterial cell. For each structure, state which cells contain it and explain one function.'},sim:'diffusion',exam:[['Explain why a root hair cell is adapted for active transport of mineral ions.',3,['large surface area','many mitochondria','energy','against concentration gradient']],['A micrograph is 48 mm wide and the real structure is 0.016 mm. Calculate the magnification.',2,['3000']]]},
    b2:{diagram:'circulation',textbook:[
      ['Organisation and digestion','Cells form tissues, tissues form organs and organs work together in organ systems. The digestive system breaks large insoluble food molecules into small soluble molecules that can be absorbed into the blood. Enzymes are biological catalysts with active sites whose shapes are affected by temperature and pH.'],
      ['Circulation and health','The heart is a double pump. Arteries carry blood away from the heart at high pressure, veins return blood and capillaries provide a short diffusion distance for exchange. Coronary heart disease reduces blood flow to heart muscle and can be treated using lifestyle changes, drugs, stents or surgery.'],
      ['Plant transport','Xylem transports water and mineral ions from roots to leaves and also supports the plant. Phloem transports dissolved sugars by translocation. Transpiration is the loss of water vapour from leaves and is affected by light intensity, temperature, humidity and air movement.']
    ],terms:[['enzyme','A biological catalyst.'],['artery','A blood vessel carrying blood away from the heart.'],['transpiration','Loss of water vapour from leaves.'],['translocation','Movement of dissolved sugars through phloem.']],worked:{title:'Enzyme rate',question:'A reaction produces 24 cm³ of product in 3 minutes. Find the mean rate.',steps:['Rate = amount of product ÷ time.','24 ÷ 3 = 8.','Mean rate = 8 cm³/min.']},activity:{title:'Blood vessel evidence',task:'Create a table linking artery, vein and capillary structure to function. Include wall thickness, lumen size, pressure and valves.'},sim:'cardiac',exam:[['Explain two ways a capillary is adapted for exchange.',2,['thin wall','one cell thick','narrow','large network','short diffusion distance']],['Explain why enzyme activity decreases above the optimum temperature.',3,['bonds break','active site changes shape','substrate no longer fits','denatured']]]},
    b3:{diagram:'pathogen',textbook:[
      ['Pathogens and disease','Communicable diseases are caused by pathogens such as viruses, bacteria, fungi and protists. They can spread by air, water, direct contact or vectors. Viruses reproduce inside cells while bacteria can reproduce independently and may release toxins.'],
      ['Defence and immunity','The skin, mucus, cilia and stomach acid provide non-specific defences. White blood cells can engulf pathogens, produce antibodies and produce antitoxins. Vaccination exposes the immune system to pathogen antigens so memory cells can respond rapidly during later infection.'],
      ['Medicines and disease control','Antibiotics treat bacterial infections but do not kill viruses. New medicines are tested for toxicity, efficacy and dose, first in preclinical studies and then in clinical trials. Separate Biology also includes monoclonal antibodies and plant disease diagnosis and defence.']
    ],terms:[['pathogen','A microorganism that causes disease.'],['antigen','A molecule recognised as foreign by the immune system.'],['antibody','A protein made by white blood cells that binds to a specific antigen.'],['vaccination','Introducing antigenic material to stimulate immunity.']],worked:{title:'Interpreting infection data',question:'Cases fall from 800 to 200 after a control measure. Calculate the percentage decrease.',steps:['Decrease = 800 − 200 = 600.','Percentage decrease = 600 ÷ 800 × 100.','= 75%.']},activity:{title:'Break the chain',task:'Choose one communicable disease and map the pathogen, route of transmission, symptoms and two methods that reduce spread.'},sim:'infection',exam:[['Explain why antibiotics should not be used to treat influenza.',2,['virus','antibiotics target bacteria','inside cells']],['Explain how vaccination can reduce the spread of a communicable disease through a population.',4,['antigens','antibodies','memory cells','fewer susceptible','less transmission']]]},
    b4:{diagram:'photosynthesis',textbook:[
      ['Photosynthesis','Photosynthesis transfers energy from light into glucose. The word equation is carbon dioxide + water → glucose + oxygen, using light and chlorophyll. The glucose may be used in respiration, converted to starch for storage, used to make cellulose, combined with nitrate ions to make amino acids, or converted to lipids.'],
      ['Limiting factors','Light intensity, carbon dioxide concentration, temperature and chlorophyll concentration can limit photosynthesis. Increasing one factor only increases the rate while that factor is limiting. Greenhouses manipulate limiting factors to increase yield but economic costs must also be considered.'],
      ['Respiration and metabolism','Aerobic respiration transfers energy using glucose and oxygen and produces carbon dioxide and water. Anaerobic respiration transfers less energy without oxygen. Metabolism is the sum of all chemical reactions in cells, including synthesis and breakdown reactions.']
    ],terms:[['photosynthesis','Endothermic process transferring light energy into glucose.'],['limiting factor','A factor in shortest supply that restricts a process.'],['aerobic respiration','Respiration using oxygen.'],['metabolism','All chemical reactions in a cell or organism.']],worked:{title:'Photosynthesis rate',question:'A plant produces 45 oxygen bubbles in 3 minutes. Find bubbles per minute.',steps:['Rate = 45 ÷ 3.','= 15 bubbles per minute.']},activity:{title:'Limiting-factor reasoning',task:'Sketch three graphs showing rate of photosynthesis against light intensity at low, medium and high carbon dioxide concentrations. Explain each plateau.'},sim:'photosynthesis',exam:[['Explain why increasing light intensity eventually stops increasing the rate of photosynthesis.',3,['another factor becomes limiting','carbon dioxide','temperature','plateau']],['State two uses of glucose made in photosynthesis.',2,['respiration','starch','cellulose','amino acids','lipids']]]},
    b5:{diagram:'control',textbook:[
      ['Homeostasis and nervous control','Homeostasis maintains optimal internal conditions. Receptors detect stimuli, coordination centres process information and effectors produce responses. Nervous responses are rapid and use electrical impulses along neurones; reflexes are fast automatic responses that reduce harm.'],
      ['Hormonal control','Hormones are chemical messengers transported in blood and usually act more slowly than nervous impulses. Insulin lowers blood glucose concentration, while glucagon raises it. Reproductive hormones coordinate the menstrual cycle and can be used in contraception and fertility treatment.'],
      ['Separate Biology extensions','Separate Biology includes the brain, eye, thermoregulation, adrenaline, thyroxine and plant hormones. Negative feedback reverses changes from a normal level and helps stabilise conditions such as body temperature, blood glucose and thyroxine concentration.']
    ],terms:[['homeostasis','Regulation of internal conditions to maintain optimum function.'],['receptor','Cell or organ that detects a stimulus.'],['effector','Muscle or gland that brings about a response.'],['negative feedback','A control process that reverses a change from the normal level.']],worked:{title:'Reaction-time data',question:'Five reaction times are 0.23, 0.25, 0.22, 0.24 and 0.31 s. Identify the anomalous result and calculate the mean of the remaining values.',steps:['0.31 s is noticeably higher than the others.','Mean = (0.23 + 0.25 + 0.22 + 0.24) ÷ 4.','= 0.235 s.']},activity:{title:'Control loop builder',task:'Build a stimulus → receptor → coordination centre → effector → response pathway for body temperature or blood glucose.'},sim:'glucose',exam:[['Describe how the body responds when blood glucose concentration becomes too high.',4,['pancreas','insulin','glucose into cells','glycogen','liver']],['Explain why a reflex action can protect the body.',2,['rapid','automatic','before conscious response','reduces injury']]]},
    b6:{diagram:'dna',textbook:[
      ['DNA, genes and reproduction','DNA is a polymer found in chromosomes. A gene is a small section of DNA that codes for a sequence of amino acids in a protein. Sexual reproduction uses meiosis to produce gametes and creates variation; asexual reproduction uses one parent and produces genetically identical offspring.'],
      ['Inheritance and variation','Alleles are different versions of genes. Genetic diagrams and Punnett squares can predict probabilities of inherited characteristics. Variation may be genetic, environmental or a combination of both.'],
      ['Evolution and biotechnology','Natural selection changes allele frequencies because organisms with advantageous inherited features are more likely to survive and reproduce. Selective breeding and genetic engineering are human-directed processes, while evidence for evolution includes fossils, resistant bacteria and classification based on relationships.']
    ],terms:[['gene','A section of DNA coding for a product such as a protein.'],['allele','An alternative version of a gene.'],['meiosis','Cell division producing genetically different gametes.'],['natural selection','Differential survival and reproduction based on inherited variation.']],worked:{title:'Genetic probability',question:'Two heterozygous parents are Aa × Aa. What is the probability of aa?',steps:['Gametes from each parent are A or a.','Possible offspring are AA, Aa, Aa, aa.','1 of 4 is aa, so probability = 25%.']},activity:{title:'Selection story',task:'Use variation → selection pressure → survival → reproduction → allele frequency to explain antibiotic resistance.'},sim:'genetics',exam:[['Explain how natural selection can produce antibiotic-resistant populations of bacteria.',4,['mutation','variation','antibiotic kills susceptible','resistant survive','reproduce','allele increases']],['What is the probability of an offspring receiving allele a from a heterozygous Aa parent?',1,['50','0.5','1/2']]]},
    b7:{diagram:'ecosystem',textbook:[
      ['Ecosystems and interdependence','An ecosystem contains interacting biotic and abiotic components. Organisms depend on each other for food, shelter, pollination and seed dispersal. Changes in temperature, light, water, soil, predators, disease or competition can alter population sizes.'],
      ['Sampling and cycles','Quadrats estimate abundance or frequency in an area and transects investigate change across a gradient. Carbon and water are recycled between living organisms and the environment. Decomposers return mineral ions and release carbon dioxide through respiration.'],
      ['Biodiversity and human impact','Biodiversity supports stable ecosystems. Human activities can reduce biodiversity through pollution, land use, deforestation and climate change, while conservation, sustainable resource use and breeding programmes can reduce impacts. Separate Biology includes trophic levels, biomass transfer and food security.']
    ],terms:[['ecosystem','Interaction of a community with non-living parts of its environment.'],['population','All organisms of one species in a habitat.'],['quadrat','A frame used to sample organisms in an area.'],['biodiversity','Variety of living organisms in an ecosystem or on Earth.']],worked:{title:'Population estimate',question:'A 0.5 m² quadrat contains a mean of 6 plants. Estimate the number in a 50 m² field.',steps:['Number of quadrats that fit = 50 ÷ 0.5 = 100.','Estimate = 100 × 6.','= 600 plants.']},activity:{title:'Fieldwork design',task:'Design a random quadrat investigation. Include independent/dependent variables, random sampling, repeats, mean and one limitation.'},sim:'quadrat',exam:[['Explain why random sampling is important when using quadrats.',2,['reduce bias','representative']],['Calculate the estimated population if a mean of 4 organisms is found per 0.25 m² in a 100 m² area.',2,['1600']]]},

    c1:{diagram:'atom',textbook:[
      ['Atoms and atomic structure','Atoms contain a tiny positively charged nucleus made of protons and neutrons, surrounded by electrons in energy levels. Atomic number equals proton number. Mass number equals protons + neutrons, and isotopes are atoms of the same element with different neutron numbers.'],
      ['Atomic models and electron structure','The accepted atomic model changed as new experimental evidence became available. Electrons occupy energy levels, and chemical properties depend strongly on outer-shell electrons. Ions form when atoms gain or lose electrons.'],
      ['Periodic table','Elements are ordered by atomic number. Elements in the same group have similar chemical properties because they have the same number of outer-shell electrons. Group 1 becomes more reactive down the group, Group 7 becomes less reactive, and Group 0 is very unreactive.']
    ],terms:[['isotope','Atoms of the same element with different numbers of neutrons.'],['atomic number','Number of protons in an atom.'],['mass number','Total number of protons and neutrons.'],['period','A horizontal row in the periodic table.']],worked:{title:'Relative atomic mass',question:'An element is 75% isotope-35 and 25% isotope-37. Find relative atomic mass.',steps:['Weighted mean = (35 × 75 + 37 × 25) ÷ 100.','= (2625 + 925) ÷ 100.','= 35.5.']},activity:{title:'Atomic model timeline',task:'Create a timeline from Dalton to the nuclear model and Bohr model. For each change, state the evidence that forced the model to change.'},sim:'atom',exam:[['An atom has 17 protons and 18 neutrons. State its atomic number and mass number.',2,['17','35']],['Explain why Group 1 metals become more reactive down the group.',3,['outer electron further','more shielding','weaker attraction','easier to lose']]]},
    c2:{diagram:'bonding',textbook:[
      ['Ionic, covalent and metallic bonding','Ionic bonding is electrostatic attraction between oppositely charged ions formed by electron transfer. Covalent bonding uses shared pairs of electrons between atoms. Metallic bonding is attraction between positive metal ions and delocalised electrons.'],
      ['Structure and properties','Giant ionic lattices have high melting points and conduct when molten or dissolved because ions can move. Simple molecular substances have weak intermolecular forces and usually low melting points. Giant covalent structures have many strong covalent bonds and often very high melting points.'],
      ['Materials','Metals conduct because delocalised electrons can carry charge. Alloys are harder than pure metals because different-sized atoms disrupt regular layers. Diamond, graphite and graphene illustrate how different carbon structures produce very different properties.']
    ],terms:[['ion','A charged particle formed by electron loss or gain.'],['covalent bond','A shared pair of electrons.'],['delocalised electron','Electron free to move through a structure.'],['intermolecular force','Attraction between separate molecules.']],worked:{title:'Explaining melting point',question:'Why does magnesium oxide have a high melting point?',steps:['It has a giant ionic lattice.','There are strong electrostatic attractions between oppositely charged ions.','A large amount of energy is needed to overcome these attractions.']},activity:{title:'Structure-property match',task:'Match sodium chloride, water, diamond, graphite and copper to bonding, structure, melting point and electrical conductivity.'},sim:'bonding',exam:[['Explain why graphite conducts electricity but diamond does not.',4,['graphite','delocalised electrons','diamond','all electrons in bonds','mobile charge']],['State the type of bonding in magnesium oxide.',1,['ionic']]]},
    c3:{diagram:'moles',textbook:[
      ['Mass and equations','Chemical equations must conserve atoms. Relative formula mass, Mr, is found by adding relative atomic masses. Balanced equations show the reacting ratio of particles and therefore the mole ratio.'],
      ['The mole','One mole contains the Avogadro constant of particles. Amount in moles = mass ÷ Mr. Mole ratios from balanced equations can then convert between amounts of reactants and products.'],
      ['Concentration and Separate Chemistry calculations','Concentration in g/dm³ = mass ÷ volume, while concentration in mol/dm³ links moles and solution volume. Separate Chemistry also includes limiting reactants, percentage yield, atom economy, titration calculations and gas volumes.']
    ],terms:[['mole','Amount of substance containing the Avogadro constant of particles.'],['Mr','Relative formula mass.'],['limiting reactant','Reactant used up first and therefore limiting product amount.'],['atom economy','Percentage of reactant atoms ending up in the desired product.']],worked:{title:'Moles from mass',question:'Calculate moles in 9.0 g of water, H₂O. Mr = 18.',steps:['Moles = mass ÷ Mr.','9.0 ÷ 18 = 0.50 mol.']},activity:{title:'Equation ratio ladder',task:'For 2H₂ + O₂ → 2H₂O, write particle, mole and mass relationships and explain which information comes from the coefficients.'},sim:'moles',exam:[['Calculate the amount in moles in 11 g of carbon dioxide, CO₂. Mr = 44.',2,['0.25']],['Explain why a measured mass can decrease during a reaction in an open flask.',2,['gas produced','gas escapes']]]},
    c4:{diagram:'electrolysis',textbook:[
      ['Reactivity and redox','The reactivity series compares how readily metals form positive ions. More reactive metals can displace less reactive metals from compounds. Oxidation is loss of electrons and reduction is gain of electrons.'],
      ['Acids and salts','Acids produce hydrogen ions in aqueous solution and alkalis produce hydroxide ions. Neutralisation forms salt and water. Soluble salts can be prepared by reacting acids with suitable metals, insoluble bases or carbonates and then crystallising the product.'],
      ['Electrolysis','Electrolysis uses electricity to decompose ionic substances. Positive ions move to the cathode and are reduced; negative ions move to the anode and are oxidised. Products in aqueous solutions depend on the ions present and their relative reactivity.']
    ],terms:[['oxidation','Loss of electrons.'],['reduction','Gain of electrons.'],['electrolyte','Ionic substance molten or dissolved so ions can move.'],['cathode','Negative electrode where reduction occurs.']],worked:{title:'Half equation',question:'Write the half equation for copper ions gaining electrons.',steps:['Copper ions are Cu²⁺.','They need two electrons to become neutral copper atoms.','Cu²⁺ + 2e⁻ → Cu.']},activity:{title:'Electrolysis predictor',task:'For molten lead bromide and aqueous sodium chloride, predict each electrode product and justify it using ion charge and reactivity.'},sim:'electrolysis',exam:[['Explain why solid sodium chloride cannot be electrolysed but molten sodium chloride can.',3,['solid ions fixed','molten ions move','carry charge']],['Complete the half equation: Al³⁺ + ___ → Al.',1,['3e','3 e','3 electrons']]]},
    c5:{diagram:'profile',textbook:[
      ['Exothermic and endothermic changes','Exothermic reactions transfer energy to the surroundings, raising surrounding temperature. Endothermic reactions take in energy from surroundings. Reaction profiles show reactant and product energy levels and activation energy.'],
      ['Bond energies','Breaking bonds requires energy; forming bonds releases energy. Overall energy change can be estimated using energy needed to break bonds − energy released when new bonds form.'],
      ['Applications and practical work','Temperature-change experiments compare reaction energy transfers. Good methods control volumes and concentrations, reduce heat loss and use repeats. Energy changes also matter in cells, hand warmers, sports injury packs and chemical processes.']
    ],terms:[['exothermic','Transfers energy to the surroundings.'],['endothermic','Takes in energy from the surroundings.'],['activation energy','Minimum energy needed for a successful reaction.'],['bond energy','Energy needed to break one mole of a specified bond.']],worked:{title:'Bond-energy calculation',question:'Bond breaking needs 720 kJ and bond making releases 850 kJ. Calculate overall energy change.',steps:['Energy change = breaking − making.','720 − 850 = −130 kJ.','Negative value means exothermic.']},activity:{title:'Reaction profile sketch',task:'Draw exothermic and endothermic profiles. Label reactants, products, activation energy and overall energy change.'},sim:'bondenergy',exam:[['Explain why breaking chemical bonds is an endothermic process.',2,['energy required','overcome attraction']],['Calculate the energy change if 950 kJ is needed to break bonds and 1200 kJ is released making bonds.',2,['-250','250 exothermic']]]},
    c6:{diagram:'collisions',textbook:[
      ['Rate of reaction','Reaction rate can be measured using change in mass, gas volume or appearance/disappearance of a substance. Mean rate = quantity changed ÷ time. A steeper graph gradient means a faster rate.'],
      ['Collision theory','Particles must collide with enough energy for a reaction. Higher temperature, concentration or gas pressure and larger surface area can increase collision frequency or the fraction of successful collisions. Catalysts provide an alternative pathway with lower activation energy.'],
      ['Reversible reactions and equilibrium','Some reactions are reversible. In a closed system, dynamic equilibrium occurs when forward and reverse reactions continue at equal rates. Changes in concentration, pressure and temperature can shift equilibrium position.']
    ],terms:[['rate','Change in amount of reactant or product per unit time.'],['catalyst','Substance that increases rate without being used up.'],['dynamic equilibrium','Forward and reverse reactions proceeding at equal rates in a closed system.'],['collision theory','Model explaining rates using particle collisions.']],worked:{title:'Mean rate',question:'60 cm³ of gas forms in 24 s. Calculate mean rate.',steps:['Rate = volume ÷ time.','60 ÷ 24 = 2.5 cm³/s.']},activity:{title:'Collision explanations',task:'For temperature, concentration, pressure and surface area, state exactly what changes at particle level and why rate increases.'},sim:'rate',exam:[['Explain using collision theory why powdered calcium carbonate reacts faster than large chips.',3,['larger surface area','more frequent collisions','more successful collisions per second']],['What does a catalyst do to activation energy?',1,['lower','reduces']]]},
    c7:{diagram:'hydrocarbon',textbook:[
      ['Crude oil and hydrocarbons','Crude oil is a mixture of hydrocarbons. Fractional distillation separates fractions by boiling point. Shorter hydrocarbons are generally more volatile, less viscous and more flammable than longer hydrocarbons.'],
      ['Alkanes and cracking','Alkanes are saturated hydrocarbons with general formula CₙH₂ₙ₊₂. Complete combustion produces carbon dioxide and water. Cracking breaks long-chain hydrocarbons into smaller useful molecules including alkenes.'],
      ['Separate Chemistry organic reactions','Separate Chemistry includes alkenes, alcohols, carboxylic acids and polymers. Alkenes decolourise bromine water because they contain a carbon-carbon double bond and can undergo addition reactions.']
    ],terms:[['hydrocarbon','Compound containing carbon and hydrogen only.'],['alkane','Saturated hydrocarbon containing only single carbon-carbon bonds.'],['alkene','Unsaturated hydrocarbon containing a carbon-carbon double bond.'],['cracking','Breaking large hydrocarbons into smaller molecules.']],worked:{title:'Alkane formula',question:'Find the molecular formula of the alkane with 6 carbon atoms.',steps:['Use CₙH₂ₙ₊₂.','n = 6, so H = 2(6)+2 = 14.','Formula = C₆H₁₄.']},activity:{title:'Fraction trends',task:'Create a trend table for chain length, boiling point, viscosity, flammability and volatility, then explain each trend in terms of intermolecular forces.'},sim:'alkane',exam:[['Explain why cracking is useful to the petrochemical industry.',3,['long chains less useful','short chains in demand','alkenes','polymers']],['State the molecular formula of pentane.',1,['C5H12','C₅H₁₂']]]},
    c8:{diagram:'chromatography',textbook:[
      ['Pure substances and chromatography','A pure substance has a fixed melting or boiling point. Chromatography separates mixtures because substances partition differently between stationary and mobile phases. Rf = distance travelled by substance ÷ distance travelled by solvent front.'],
      ['Gas tests','Hydrogen gives a squeaky pop with a lit splint. Oxygen relights a glowing splint. Carbon dioxide turns limewater cloudy. Chlorine bleaches damp litmus paper.'],
      ['Separate Chemistry ion tests','Separate Chemistry includes flame tests, precipitation tests for metal ions, carbonate, halide and sulfate tests, and instrumental methods such as flame emission spectroscopy. Instrumental methods can be fast, sensitive and accurate.']
    ],terms:[['chromatography','Technique used to separate components of a mixture.'],['Rf value','Distance travelled by substance divided by distance travelled by solvent front.'],['precipitate','Insoluble solid formed in a solution reaction.'],['formulation','Mixture designed as a useful product.']],worked:{title:'Rf calculation',question:'A dye moves 4.2 cm while the solvent front moves 6.0 cm. Find Rf.',steps:['Rf = 4.2 ÷ 6.0.','= 0.70.']},activity:{title:'Unknown analysis',task:'Design a decision tree using gas tests and chromatography to identify unknown samples from evidence.'},sim:'rf',exam:[['A spot travels 3.6 cm and the solvent front 4.5 cm. Calculate Rf.',2,['0.8','0.80']],['Describe the test for oxygen gas.',2,['glowing splint','relights']]]},
    c9:{diagram:'atmosphere',textbook:[
      ['Earth’s atmosphere','Modern dry air is about 78% nitrogen and 21% oxygen with small amounts of argon, carbon dioxide and other gases. The early atmosphere was very different and changed through volcanic activity, cooling, ocean formation and photosynthesis.'],
      ['Greenhouse effect and climate','Greenhouse gases absorb and re-emit infrared radiation, warming the atmosphere. Human activity has increased concentrations of carbon dioxide and methane, contributing to climate change. Scientific conclusions use evidence while acknowledging uncertainty.'],
      ['Pollution','Incomplete combustion can produce carbon monoxide and soot. High-temperature engines can produce nitrogen oxides, and sulfur impurities in fuels can produce sulfur dioxide. These pollutants can harm health and ecosystems.']
    ],terms:[['greenhouse gas','Atmospheric gas that absorbs and re-emits infrared radiation.'],['carbon footprint','Total greenhouse gas emissions caused directly and indirectly by an activity or product.'],['particulate','Tiny solid particles suspended in air.'],['climate change','Long-term change in average climate patterns.']],worked:{title:'Percentage change',question:'CO₂ rises from 280 ppm to 420 ppm. Calculate percentage increase.',steps:['Increase = 140 ppm.','140 ÷ 280 × 100 = 50%.']},activity:{title:'Evidence vs claim',task:'Separate evidence, scientific explanation and policy choice in a short climate-change scenario. Explain why those categories should not be confused.'},sim:'atmosphere',exam:[['Explain how increasing carbon dioxide can cause global warming.',3,['infrared','absorbed','re-emitted','less energy escapes']],['Name one pollutant produced by incomplete combustion.',1,['carbon monoxide','soot','particulates']]]},
    c10:{diagram:'lifecycle',textbook:[
      ['Resources and potable water','Humans use finite and renewable resources for food, energy, materials and water. Potable water is safe to drink but is not necessarily pure. Treatment depends on source and may include filtration, sterilisation and desalination.'],
      ['Life-cycle assessment and recycling','Life-cycle assessment considers environmental impacts of raw material extraction, manufacture, use and disposal. Recycling can reduce raw-material extraction and landfill, although collection and processing also use energy.'],
      ['Separate Chemistry industrial materials','Separate Chemistry includes corrosion prevention, alloys, ceramics, polymers, composites, the Haber process and NPK fertilisers. Industrial conditions are compromises between rate, yield, energy cost and equipment cost.']
    ],terms:[['potable','Safe to drink.'],['life-cycle assessment','Evaluation of environmental impact across a product’s life.'],['corrosion','Destruction of materials by chemical reactions with the environment.'],['composite','Material made by combining materials with different properties.']],worked:{title:'Resource comparison',question:'A recycled process uses 2.4 MJ instead of 6.0 MJ. Calculate percentage energy saving.',steps:['Saving = 6.0 − 2.4 = 3.6 MJ.','3.6 ÷ 6.0 × 100 = 60%.']},activity:{title:'LCA challenge',task:'Compare reusable and single-use bottles across raw materials, manufacture, transport, use and disposal. Identify where data uncertainty could change the conclusion.'},sim:'resources',exam:[['Explain why life-cycle assessments can give different conclusions.',2,['different data','weighting subjective','boundaries differ']],['State two stages used to produce potable water from fresh water.',2,['filtration','sterilisation','chlorine','ozone','UV']]]},

    p1:{diagram:'energy',textbook:[
      ['Energy stores and transfers','Energy is stored in kinetic, thermal, gravitational, elastic, chemical, magnetic, electrostatic and nuclear stores. Energy is transferred mechanically, electrically, by heating or by radiation. In a closed system total energy is conserved.'],
      ['Calculations','Key relationships include kinetic energy = ½mv², gravitational potential energy = mgh, elastic energy = ½ke² and power = energy transferred ÷ time. Always use SI units and show substitutions.'],
      ['Efficiency and resources','Useful energy transfers are often accompanied by dissipated energy, usually to thermal stores. Efficiency compares useful output with total input. Energy-resource choices involve reliability, environmental impact, start-up time, cost and sustainability.']
    ],terms:[['power','Rate of energy transfer.'],['efficiency','Useful output divided by total input.'],['dissipation','Spreading energy into less useful thermal stores.'],['system','Object or group of objects being analysed.']],worked:{title:'Kinetic energy',question:'Calculate the kinetic energy of a 1200 kg car travelling at 15 m/s.',steps:['Ek = ½mv².','= 0.5 × 1200 × 15².','= 135,000 J.']},activity:{title:'Energy pathway audit',task:'Choose a kettle, car or falling object. Identify initial store, transfer pathway, final stores and any dissipated energy.'},sim:'energy',exam:[['Calculate the kinetic energy of a 2.0 kg object moving at 6.0 m/s.',2,['36']],['Explain why no real device can be more than 100% efficient.',2,['energy conserved','useful output cannot exceed input']]]},
    p2:{diagram:'circuit',textbook:[
      ['Current, potential difference and resistance','Current is the rate of flow of charge: Q = It. Potential difference is energy transferred per unit charge. Resistance opposes current and V = IR links potential difference, current and resistance.'],
      ['Series and parallel circuits','Current is the same throughout a series circuit and potential differences share across components. In parallel, potential difference is the same across branches and currents add at junctions. Resistance and component behaviour can be investigated using I–V graphs.'],
      ['Power, mains and the National Grid','Electrical power can be found using P = VI or P = I²R. Domestic mains is alternating current; safety features include insulation, fuses, circuit breakers and earth wires. The National Grid uses transformers and high transmission potential differences to reduce energy losses.']
    ],terms:[['current','Rate of flow of electric charge.'],['potential difference','Energy transferred per unit charge.'],['resistance','Opposition to current.'],['alternating current','Current that repeatedly changes direction.']],worked:{title:'Ohm’s law',question:'A resistor has 12 V across it and current 0.40 A. Find resistance.',steps:['R = V ÷ I.','12 ÷ 0.40 = 30 Ω.']},activity:{title:'Circuit prediction',task:'Predict how current and potential difference change when identical resistors are added in series and then in parallel. Justify each prediction.'},sim:'ohm',exam:[['Calculate the current through a 24 Ω resistor connected across 12 V.',2,['0.5','0.50']],['Explain why power is transmitted at high potential difference on the National Grid.',3,['lower current','less heating','I squared R','less energy loss']]]},
    p3:{diagram:'particles',textbook:[
      ['Density and states','Density = mass ÷ volume. Solids, liquids and gases differ because of particle arrangement, movement and forces. Changes of state are physical changes and conserve mass.'],
      ['Internal energy','Internal energy is the total kinetic and potential energy of particles in a system. Heating can increase temperature by increasing particle kinetic energy or can change state by increasing particle potential energy.'],
      ['Specific heat and latent heat','Specific heat capacity is energy required to raise the temperature of 1 kg by 1°C: ΔE = mcΔθ. Specific latent heat is energy needed to change state of 1 kg without a temperature change: E = mL.']
    ],terms:[['density','Mass per unit volume.'],['internal energy','Total kinetic and potential energy of particles in a system.'],['specific heat capacity','Energy to raise 1 kg by 1°C.'],['latent heat','Energy transferred during change of state without temperature change.']],worked:{title:'Density',question:'A block has mass 540 g and volume 200 cm³. Find density.',steps:['ρ = m ÷ V.','540 ÷ 200 = 2.7 g/cm³.']},activity:{title:'Heating-curve explanation',task:'Sketch a heating curve and annotate sloping and flat sections using kinetic energy, potential energy and state changes.'},sim:'density',exam:[['Calculate the density of a 0.60 kg object with volume 0.00025 m³.',2,['2400']],['Explain why temperature stays constant while a substance melts.',3,['energy supplied','overcomes forces','potential energy increases','kinetic energy unchanged']]]},
    p4:{diagram:'decay',textbook:[
      ['Atomic nucleus and radiation','Atoms have nuclei containing protons and neutrons. Unstable nuclei can decay randomly and emit alpha, beta or gamma radiation. These radiations differ in ionising power and penetration.'],
      ['Half-life','Radioactive decay is random for individual nuclei but predictable for large samples. Half-life is the time for activity or number of undecayed nuclei to fall to half its value. Background radiation comes from natural and artificial sources.'],
      ['Uses, risks and nuclear energy','Ionising radiation can damage living cells, so risk depends on dose and exposure. Contamination places radioactive material on or inside an object, while irradiation is exposure to radiation. Separate Physics includes fission and fusion.']
    ],terms:[['activity','Rate at which a source decays, measured in becquerels.'],['half-life','Time for activity or undecayed nuclei to halve.'],['contamination','Unwanted radioactive material on or inside an object.'],['irradiation','Exposure to radiation from a source.']],worked:{title:'Half-life',question:'A sample starts at 800 counts/min and has a half-life of 3 h. What is the count after 9 h?',steps:['9 h is three half-lives.','800 → 400 → 200 → 100.','Count = 100 counts/min.']},activity:{title:'Risk-benefit judgement',task:'Compare one medical use of ionising radiation with its risks. State how exposure can be reduced using time, distance and shielding.'},sim:'halflife',exam:[['A source has activity 640 Bq and half-life 5 days. Find activity after 15 days.',2,['80']],['Explain the difference between contamination and irradiation.',2,['radioactive material on or inside','exposure from source']]]},
    p5:{diagram:'force',textbook:[
      ['Forces and interactions','Forces are vectors and may be contact or non-contact. Resultant force determines acceleration. Weight = mg, work done = force × distance moved in the force direction, and elastic behaviour can be described with F = ke within the limit of proportionality.'],
      ['Motion and graphs','Speed = distance ÷ time and acceleration = change in velocity ÷ time. Gradient of a distance–time graph gives speed, gradient of a velocity–time graph gives acceleration, and area under a velocity–time graph gives displacement.'],
      ['Newton’s laws, stopping and momentum','Newton’s laws connect resultant force, mass and acceleration. Stopping distance = thinking distance + braking distance. Momentum p = mv and force can be linked to rate of change of momentum.']
    ],terms:[['resultant force','Single force with same effect as all forces combined.'],['acceleration','Rate of change of velocity.'],['momentum','Mass × velocity.'],['stopping distance','Thinking distance + braking distance.']],worked:{title:'Newton’s second law',question:'A 900 kg car accelerates at 2.5 m/s². Calculate resultant force.',steps:['F = ma.','900 × 2.5 = 2250 N.']},activity:{title:'Graph lab',task:'Draw a velocity–time graph containing acceleration, constant velocity and deceleration. Calculate one gradient and one area.'},sim:'force',exam:[['Calculate the acceleration of a 1200 kg car when the resultant force is 3600 N.',2,['3']],['Explain two factors that increase braking distance.',4,['speed','wet','icy','worn tyres','worn brakes','less friction']]]},
    p6:{diagram:'wave',textbook:[
      ['Wave properties','Waves transfer energy without transferring matter overall. Transverse oscillations are perpendicular to travel direction; longitudinal oscillations are parallel. Wave speed, frequency and wavelength are linked by v = fλ.'],
      ['Electromagnetic spectrum','All electromagnetic waves travel at the same speed in a vacuum but differ in frequency and wavelength. Different regions are used for communication, heating, imaging and treatment; higher-frequency ionising waves can damage cells.'],
      ['Reflection, refraction and Separate Physics','Reflection changes direction at a boundary and refraction occurs when wave speed changes between media. Separate Physics includes sound, seismic waves, lenses, colour and black-body radiation.']
    ],terms:[['frequency','Number of waves passing a point per second.'],['wavelength','Distance between equivalent points on adjacent waves.'],['refraction','Change in direction caused by change in wave speed.'],['electromagnetic wave','Transverse wave of oscillating electric and magnetic fields.']],worked:{title:'Wave speed',question:'A wave has frequency 50 Hz and wavelength 0.80 m. Find speed.',steps:['v = fλ.','50 × 0.80 = 40 m/s.']},activity:{title:'Spectrum organiser',task:'Order the electromagnetic spectrum by frequency and attach one use and one possible hazard to each region.'},sim:'waves',exam:[['Calculate wavelength for a 340 m/s wave of frequency 170 Hz.',2,['2']],['Explain why radio waves and gamma rays travel at the same speed in a vacuum.',2,['both electromagnetic','same speed in vacuum']]]},
    p7:{diagram:'magnet',textbook:[
      ['Magnetic fields and electromagnets','Magnets exert forces through magnetic fields. Field lines show direction from north to south outside a magnet. A current in a wire produces a magnetic field; a solenoid produces a stronger, more uniform field that can be enhanced with an iron core.'],
      ['Motor effect','A current-carrying conductor in a magnetic field experiences a force if it is not parallel to the field. This motor effect is used in motors. Force depends on magnetic flux density, current and conductor length.'],
      ['Separate Physics induction','Separate Physics includes electromagnetic induction, generators, microphones and transformers. A changing magnetic field through a conductor can induce a potential difference, and transformers change alternating potential difference using different coil turns.']
    ],terms:[['magnetic field','Region where magnetic materials or moving charges experience a force.'],['solenoid','Coil of wire producing a magnetic field when current flows.'],['motor effect','Force on a current-carrying conductor in a magnetic field.'],['induction','Generation of potential difference by changing magnetic flux.']],worked:{title:'Transformer ratio',question:'A transformer has 500 primary turns and 50 secondary turns. Primary pd is 230 V. Find secondary pd.',steps:['Vp/Vs = Np/Ns.','230/Vs = 500/50 = 10.','Vs = 23 V.']},activity:{title:'Field sketch',task:'Draw the field around a bar magnet and a current-carrying solenoid. Mark field direction and where the field is strongest.'},sim:'transformer',exam:[['Explain how increasing current in a solenoid affects its magnetic field.',2,['field stronger','current produces field']],['A transformer has 1000 primary turns and 100 secondary turns with 240 V primary. Calculate secondary pd.',2,['24']]]},
    p8:{diagram:'orbit',textbook:[
      ['Solar System and gravity','The Solar System contains the Sun, planets, dwarf planets, moons, asteroids and comets. Gravity provides the centripetal force that keeps planets and satellites in orbit. Circular orbital speed depends on orbital radius and the central mass.'],
      ['Stellar evolution and elements','Stars form from clouds of gas and dust. Main-sequence stars balance gravitational collapse with outward pressure from fusion. Low-mass and high-mass stars follow different life cycles; fusion makes elements up to iron, while heavier elements form in supernovae.'],
      ['Red-shift and the expanding Universe','Light from distant galaxies is red-shifted, showing that they are moving away. More distant galaxies generally recede faster, supporting an expanding Universe. Red-shift and cosmic microwave background evidence support the Big Bang model.']
    ],terms:[['orbit','Curved path under a centripetal force such as gravity.'],['fusion','Joining light nuclei and releasing energy.'],['red-shift','Increase in observed wavelength from a receding source.'],['Big Bang model','Model in which the Universe expanded from a very hot dense early state.']],worked:{title:'Light travel reasoning',question:'Why do astronomers say that observing a galaxy 2 million light-years away shows the past?',steps:['Light travels at a finite speed.','The light has travelled for 2 million years.','We see the galaxy as it was 2 million years ago.']},activity:{title:'Star life-cycle map',task:'Build separate flow diagrams for a Sun-like star and a much more massive star, including the main fusion stages and final remnants.'},sim:'orbit',exam:[['Explain what red-shift of light from a distant galaxy indicates.',2,['wavelength increased','galaxy moving away']],['Explain why a planet can move at constant speed but still accelerate in a circular orbit.',3,['velocity changes direction','acceleration is change in velocity','centripetal force']]]}
  };

  function tokenise(text=''){
    return text.toLowerCase().replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(w=>w.length>3 && !['and','with','from','into','using','their','this','that'].includes(w));
  }
  function lessonChapter(topicId, lessonTitle, index=0){
    const g=guides[topicId];
    if(!g) return null;
    const target=new Set(tokenise(lessonTitle));
    let best=g.textbook[0],score=-1;
    g.textbook.forEach(section=>{
      const sectionTokens=tokenise(section[0]+' '+section[1]);
      const s=sectionTokens.reduce((n,w)=>n+(target.has(w)?1:0),0);
      if(s>score){score=s;best=section;}
    });
    if(score<=0) best=g.textbook[index%g.textbook.length];
    return best;
  }
  function getLesson(topic, lessonTitle, index=0){
    const g=guides[topic.id];
    if(!g) return null;
    const section=lessonChapter(topic.id,lessonTitle,index);
    const retrieval=topic.quiz[index%topic.quiz.length];
    return {
      title:lessonTitle,
      objectives:[`Describe the key science in ${lessonTitle.toLowerCase()}.`,`Apply the ideas to an unfamiliar GCSE-style context.`,`Use precise scientific vocabulary and evidence in an exam answer.`],
      section,
      terms:g.terms,
      worked:g.worked,
      check:retrieval,
      examTip:`For ${topic.code}, name the scientific idea first, then link it to the evidence or change described in the question. Show every calculation step and include units.`
    };
  }
  return {guides,getLesson};
})();